version: '3.9'
services:
  task-tracker:
    container_name: task-tracker
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - task-tracker-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://task-tracker-db:5432/tasktrackerdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  task-tracker-db:
    image: postgres
    container_name: task-tracker-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasktrackerdb