version: '3.9'
services:
  task-tracker:
    container_name: task-tracker
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - task-tracker-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://task-tracker-db:5432/${DATABASE_NAME}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USER}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
  task-tracker-db:
    image: postgres
    container_name: task-tracker-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}